// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.0
// Source: auth.proto

package server

import (
	"context"

	"auth-service/rpc/auth"
	"auth-service/rpc/internal/logic"
	"auth-service/rpc/internal/svc"
)

type AuthServer struct {
	svcCtx *svc.ServiceContext
	auth.UnimplementedAuthServer
}

func NewAuthServer(svcCtx *svc.ServiceContext) *AuthServer {
	return &AuthServer{
		svcCtx: svcCtx,
	}
}

// 健康检查
func (s *AuthServer) HealthCheck(ctx context.Context, in *auth.Empty) (*auth.BaseResponse, error) {
	l := logic.NewHealthCheckLogic(ctx, s.svcCtx)
	return l.HealthCheck(in)
}

// 登录
func (s *AuthServer) Login(ctx context.Context, in *auth.LoginReq) (*auth.LoginResp, error) {
	l := logic.NewLoginLogic(ctx, s.svcCtx)
	return l.Login(in)
}
