// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.0

package types

type BaseResponse struct {
	Code    int64       `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,optional"`
}

type CaptchaResp struct {
	CaptchaID    string `json:"captchaId"`
	CaptchaImage string `json:"captchaImage"` // base64 编码过的图片
	ExpiresIn    int64  `json:"expiresIn"`    // 有效期（秒）
}

type ChangePasswordReq struct {
	OldPassword string `json:"oldPassword" validate:"required"`
	NewPassword string `json:"newPassword" validate:"required,min=6,max=30"`
}

type CheckPermissionReq struct {
	UserID   string `json:"userId" validate:"required"`
	Resource string `json:"resource" validate:"required"`
	Action   string `json:"action" validate:"required"` // read, write, delete等
}

type CheckPermissionResp struct {
	HasPermission bool   `json:"hasPermission"`
	Message       string `json:"message,optional"`
}

type LoginReq struct {
	Username      string `json:"username" validate:"required"` // 用户名
	Password      string `json:"password" validate:"required"` // 密码
	CaptchaID     string `json:"captchaId,optional"`
	CaptchaAnswer string `json:"captchaAnswer,optional"` // 用户填写的验证码
}

type LoginResp struct {
	UserID       string `json:"userId"`
	Username     string `json:"username"`
	Email        string `json:"email,optional"`
	Avatar       string `json:"avatar,optional"`
	AccessToken  string `json:"accessToken"`
	RefreshToken string `json:"refreshToken"`
	ExpiresIn    int64  `json:"expiresIn"`                  // 有效期（秒）
	TokenType    string `json:"tokenType" default:"Bearer"` // 令牌类型
}

type LogoutReq struct {
	RefreshToken string `json:"refreshToken,optional"`
}

type RefreshTokenReq struct {
	RefreshToken string `json:"refreshToken" validate:"required"`
}

type RefreshTokenResp struct {
	AccessToken  string `json:"accessToken"`
	RefreshToken string `json:"refreshToken"`
	ExpiresIn    int64  `json:"expiresIn"`
}

type RegisterReq struct {
	Username      string `json:"username" validate:"required,min=3,max=20"`
	Password      string `json:"password" validate:"required,min=6,max=30"`
	Email         string `json:"email" validate:"required,email"`
	Phone         string `json:"phone,optional" validate:"omitempty,phone"`
	Nickname      string `json:"nickname,optional"`
	CaptchaID     string `json:"captchaId,optional"`
	CaptchaAnswer string `json:"captchaAnswer,optional"`
}

type RegisterResp struct {
	UserID    string `json:"userId"`
	Username  string `json:"username"`
	Email     string `json:"email"`
	CreatedAt int64  `json:"createdAt"`
}

type ResetPasswordReq struct {
	Email         string `json:"email" validate:"required,email"`
	CaptchaID     string `json:"captchaId" validate:"required"`
	CaptchaAnswer string `json:"captchaAnswer" validate:"required"`
	NewPassword   string `json:"newPassword" validate:"required,min=6,max=30"`
}

type VerifyTokenReq struct {
	Token string `json:"token" validate:"required"`
}

type VerifyTokenResp struct {
	IsValid   bool   `json:"isValid"`
	UserID    string `json:"userId,optional"`
	Username  string `json:"username,optional"`
	ExpiresAt int64  `json:"expiresAt,optional"`
	Message   string `json:"message,optional"`
}
