// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.0

package types

type BaseResponse struct {
	Code    int64       `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,optional"`
}

type CaptchaResp struct {
	CaptchaID    string `json:"captchaId"`
	CaptchaImage string `json:"captchaImage"` // base64 编码过的图片
	ExpiresIn    int64  `json:"expiresIn"`    // 验证码有效期（秒）
}

type ChangePasswordReq struct {
	OldPassword string `json:"oldPassword" validate:"required"`
	NewPassword string `json:"newPassword" validate:"required,min=6,max=30"`
}

type CheckPermissionReq struct {
	UserID   string `json:"userId" validate:"required"`
	Resource string `json:"resource" validate:"required"`
	Action   string `json:"action" validate:"required"` // read, write, delete等
}

type CheckPermissionResp struct {
	HasPermission bool   `json:"hasPermission"`
	Message       string `json:"message,optional"`
}

type LoginReq struct {
	Username      string `json:"username" validate:"required"` // 用户名 (或 邮箱/手机号)
	Password      string `json:"password" validate:"required"` // 密码
	CaptchaID     string `json:"captchaId,optional"`           // 验证码ID (从获取验证码接口取得)
	CaptchaAnswer string `json:"captchaAnswer,optional"`       // 用户实际填写的验证码
}

type LoginResp struct {
	UserID           string `json:"userId"`                     // 对外返回 Public ID 作为用户标识
	Username         string `json:"username"`                   // 用户名
	Email            string `json:"email,optional"`             // 邮箱
	AccessToken      string `json:"accessToken"`                // 访问令牌
	AccessExpiresAt  int64  `json:"accessExpiresAt"`            // 访问令牌的过期时间（秒）
	RefreshToken     string `json:"refreshToken"`               // 刷新令牌
	RefreshExpiresAt int64  `json:"refreshExpiresAt"`           // 刷新令牌的过期时间（秒）
	TokenType        string `json:"tokenType" default:"Bearer"` // 令牌类型
}

type LogoutReq struct {
	AccessToken  string `json:"accessToken,optional"`
	RefreshToken string `json:"refreshToken,optional"`
}

type RefreshTokenReq struct {
	RefreshToken string `json:"refreshToken" validate:"required"`
}

type RefreshTokenResp struct {
	AccessToken      string `json:"accessToken"`                // 访问令牌
	AccessExpiresAt  int64  `json:"accessExpiresAt"`            // 访问令牌的过期时间（秒）
	RefreshToken     string `json:"refreshToken"`               // 刷新令牌
	RefreshExpiresAt int64  `json:"refreshExpiresAt"`           // 刷新令牌的过期时间（秒）
	TokenType        string `json:"tokenType" default:"Bearer"` // 令牌类型
}

type RegisterReq struct {
	Username      string `json:"username" validate:"required,min=3,max=20"`
	Password      string `json:"password" validate:"required,min=6,max=30"`
	Email         string `json:"email" validate:"required,email"`
	Phone         string `json:"phone,optional" validate:"omitempty,phone"`
	Nickname      string `json:"nickname,optional"`
	CaptchaID     string `json:"captchaId,optional"`
	CaptchaAnswer string `json:"captchaAnswer,optional"`
}

type RegisterResp struct {
	UserID    string `json:"userId"`
	Username  string `json:"username"`
	Email     string `json:"email"`
	CreatedAt int64  `json:"createdAt"`
}

type ResetPasswordReq struct {
	Email         string `json:"email" validate:"required,email"`
	CaptchaID     string `json:"captchaId,optional"`
	CaptchaAnswer string `json:"captchaAnswer,optional"`
}

type VerifyTokenReq struct {
	AccessToken string `json:"accessToken" validate:"required"`
}

type VerifyTokenResp struct {
	IsValid   bool   `json:"isValid"`
	Message   string `json:"message,optional"`
	UserID    string `json:"userId,optional"`
	Username  string `json:"username,optional"`
	ExpiresAt int64  `json:"expiresAt,optional"`
	TokenID   string `json:"tokenId,optional"`
	TokenType string `json:"tokenType" default:"Bearer"`
}
