// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.0

package mysql

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	userFieldNames          = builder.RawFieldNames(&User{})
	userRows                = strings.Join(userFieldNames, ",")
	userRowsExpectAutoSet   = strings.Join(stringx.Remove(userFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	userRowsWithPlaceHolder = strings.Join(stringx.Remove(userFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	userModel interface {
		Insert(ctx context.Context, data *User) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*User, error)
		FindOneByEmail(ctx context.Context, email string) (*User, error)
		FindOneByPublicId(ctx context.Context, publicId string) (*User, error)
		FindOneByUsername(ctx context.Context, username string) (*User, error)
		Update(ctx context.Context, data *User) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultUserModel struct {
		conn  sqlx.SqlConn
		table string
	}

	User struct {
		Id                  uint64         `db:"id"`                    // 自增主键，内部关联使用
		PublicId            string         `db:"public_id"`             // 对外暴露的UserID，避免ID枚举攻击
		Nickname            sql.NullString `db:"nickname"`              // 昵称
		Username            string         `db:"username"`              // 用户名
		Email               string         `db:"email"`                 // 邮箱
		EmailVerified       int64          `db:"email_verified"`        // 邮箱是否已验证 (0-未验证, 1-已验证)
		Phone               sql.NullString `db:"phone"`                 // 手机号 (国际格式)
		PhoneVerified       int64          `db:"phone_verified"`        // 手机号是否已验证 (0-未验证, 1-已验证)
		PasswordHash        string         `db:"password_hash"`         // 加密后的密码
		PasswordSalt        sql.NullString `db:"password_salt"`         // 密码盐
		MfaSecret           sql.NullString `db:"mfa_secret"`            // MFA秘钥 (加密存储)
		MfaEnabled          int64          `db:"mfa_enabled"`           // 是否启用了MFA (0-未启用, 1-启用)
		AccountStatus       uint64         `db:"account_status"`        // 账户状态 (1-正常, 2-锁定, 3-禁用)
		FailedLoginAttempts uint64         `db:"failed_login_attempts"` // 连续失败登录次数
		LockoutUntil        sql.NullTime   `db:"lockout_until"`         // 账户锁定截止时间
		LastLoginAt         sql.NullTime   `db:"last_login_at"`         // 最后一次登录时间
		CreatedAt           time.Time      `db:"created_at"`            // 创建时间
		UpdatedAt           time.Time      `db:"updated_at"`            // 更新时间
		DeletedAt           sql.NullTime   `db:"deleted_at"`            // 软删除时间
	}
)

func newUserModel(conn sqlx.SqlConn) *defaultUserModel {
	return &defaultUserModel{
		conn:  conn,
		table: "`user`",
	}
}

func (m *defaultUserModel) Delete(ctx context.Context, id uint64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultUserModel) FindOne(ctx context.Context, id uint64) (*User, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", userRows, m.table)
	var resp User
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUserModel) FindOneByEmail(ctx context.Context, email string) (*User, error) {
	var resp User
	query := fmt.Sprintf("select %s from %s where `email` = ? limit 1", userRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, email)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUserModel) FindOneByPublicId(ctx context.Context, publicId string) (*User, error) {
	var resp User
	query := fmt.Sprintf("select %s from %s where `public_id` = ? limit 1", userRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, publicId)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUserModel) FindOneByUsername(ctx context.Context, username string) (*User, error) {
	var resp User
	query := fmt.Sprintf("select %s from %s where `username` = ? limit 1", userRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, username)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUserModel) Insert(ctx context.Context, data *User) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, userRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.PublicId, data.Username, data.Email, data.EmailVerified, data.Phone, data.PhoneVerified, data.PasswordHash, data.PasswordSalt, data.MfaSecret, data.MfaEnabled, data.AccountStatus, data.FailedLoginAttempts, data.LockoutUntil, data.LastLoginAt, data.DeletedAt)
	return ret, err
}

func (m *defaultUserModel) Update(ctx context.Context, newData *User) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, userRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.PublicId, newData.Username, newData.Email, newData.EmailVerified, newData.Phone, newData.PhoneVerified, newData.PasswordHash, newData.PasswordSalt, newData.MfaSecret, newData.MfaEnabled, newData.AccountStatus, newData.FailedLoginAttempts, newData.LockoutUntil, newData.LastLoginAt, newData.DeletedAt, newData.Id)
	return err
}

func (m *defaultUserModel) tableName() string {
	return m.table
}
