networks:
  dev-stack:
    name: dev-stack
    driver: bridge

volumes:
  redis-data:
  mysql-data:

services:
  # Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity
    depends_on:
      - redis
      - mysql
    networks:
      - dev-stack
    environment:
      - MYSQL_HOST=mysql
      - REDIS_HOST=redis

  # MySQL https://dev.mysql.com/doc/refman/8.4/en/
  mysql:
    image: docker.io/mysql:8
    container_name: mysql
    restart: unless-stopped
    ports:
      - "${MYSQL_PORT:-3306}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:?root password is required}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-testing}
      MYSQL_USER: ${MYSQL_USER:-testing}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:?password is required}
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - dev-stack

  # Redis https://redis.io/docs/latest/operate/oss_and_stack/
  redis:
    image: docker.io/redis:8
    container_name: redis
    restart: unless-stopped
    command: redis-server --requirepass ${REDIS_PASSWORD:?password is required}
    ports:
      - "${REDIS_PORT:-6379}:6379"
    volumes:
      - redis-data:/data
    networks:
      - dev-stack
